### ISSUE TITLE
Changing current/synapse parameters during clamp

### ISSUE THREAD

**Issue by kernfel** [tnowotny/stdpc#1]
As far as I can tell, all synapse and current parameters are adjustable, through the UI and by script, while the clamp thread is running. There are two notable exceptions:
(1) Changing the assigned channels doesn't have an effect until the clamp cycle is restarted. This is unavoidable and perfectly fine.
(2) Changing a synapse/current type, or turning it on/off, has no effect when done through the GUI. In contrast, scripts can change the `active` flag, which is respected dynamically.
Is the inability to do this through the GUI intentional, or would it make sense to allow manual changes?

**Comment by tnowotny** [comment]
This setup was intentional. It came from a mode of working, where experimenters would run Dynamic Clamp but might want to already enter changed values etc for the subsequent run. This way they'd be ready to hit the start button when the prep was ready for it.
If changes during the clamping are intended, one more likely than not would want to have them timed carefully, and hence should probably use scripting. I think this is a good way to do it - what do you think @kernfel ?

**Comment by kernfel** [comment]
Ah, I missed the fact that parameter values aren't saved to the data structs either. Right, that makes perfect sense then. I'll stick with that functionality. Thanks!
